const defaultBooks = [
  { title: 'Tomorrow, and Tomorrow, and Tomorrow', author: 'Gabrielle Zevin', category: 'Fiction', copies: 4, loaned: true },
  { title: 'The Creative Act', author: 'Rick Rubin', category: 'Arts & Culture', copies: 2, loaned: false },
  { title: 'Braiding Sweetgrass', author: 'Robin Wall Kimmerer', category: 'Nature', copies: 3, loaned: true },
  { title: 'The Vanishing Half', author: 'Brit Bennett', category: 'Fiction', copies: 2, loaned: false },
  { title: 'A Field Guide to Getting Lost', author: 'Rebecca Solnit', category: 'Essays', copies: 1, loaned: false },
  { title: 'Sea of Tranquility', author: 'Emily St. John Mandel', category: 'Fiction', copies: 3, loaned: false }
];
const members = [{ name: 'Maya Thompson', initials: 'MT', loans: 3, joined: 'Joined Jan 2024' }, { name: 'Elliot Brooks', initials: 'EB', loans: 1, joined: 'Joined Mar 2024' }, { name: 'Nora Patel', initials: 'NP', loans: 2, joined: 'Joined Apr 2024' }, { name: 'Sam Rivera', initials: 'SR', loans: 0, joined: 'Joined May 2024' }];
const activities = [{ initials: 'MT', name: 'Maya Thompson', action: 'borrowed', book: 'Tomorrow, and Tomorrow, and Tomorrow', time: '12 minutes ago' }, { initials: 'EB', name: 'Elliot Brooks', action: 'returned', book: 'The Creative Act', time: '1 hour ago' }, { initials: 'NP', name: 'Nora Patel', action: 'borrowed', book: 'Braiding Sweetgrass', time: '3 hours ago' }];
let books = JSON.parse(localStorage.getItem('leaf-ledger-books') || 'null') || defaultBooks;
const $ = (selector) => document.querySelector(selector);
function bookRow(book, index, catalog = false) { const coverClass = index % 3 === 1 ? 'green' : index % 3 === 2 ? 'blue' : ''; const status = book.loaned ? '<span class="status">On loan</span>' : '<span class="status">Available</span>'; return catalog ? `<tr><td><div class="book-cell"><span class="book-cover ${coverClass}">${book.title.charAt(0)}</span>${book.title}</div></td><td>${book.author}</td><td>${book.category}</td><td>${book.copies}</td><td>${status}</td><td><button class="row-action" data-loan="${index}">${book.loaned ? 'Return' : 'Loan'}</button></td></tr>` : `<tr><td><div class="book-cell"><span class="book-cover ${coverClass}">${book.title.charAt(0)}</span>${book.title}</div></td><td>${index ? 'Elliot Brooks' : 'Maya Thompson'}</td><td>${index ? 'May 18, 2024' : 'May 20, 2024'}</td><td>${index ? 'May 30, 2024' : 'Jun 03, 2024'}</td><td>${index === 2 ? '<span class="status overdue">Overdue</span>' : status}</td><td><button class="row-action" data-loan="${index}">Return</button></td></tr>`; }
function render() { $('#total-books').textContent = (1248 + books.length - defaultBooks.length).toLocaleString(); $('#loaned-books').textContent = 86 + books.filter((book) => book.loaned).length - 2; $('#catalog-table').innerHTML = filteredBooks().map((book, index) => bookRow(book, index, true)).join(''); $('#loan-table').innerHTML = books.filter((book) => book.loaned).slice(0, 4).map((book, index) => bookRow(book, index)).join('') || '<tr><td colspan="6">No active loans right now.</td></tr>'; $('#activity-list').innerHTML = activities.map(activityMarkup).join(''); $('#full-activity-list').innerHTML = activities.concat(activities).map(activityMarkup).join(''); $('#member-grid').innerHTML = members.map((member) => `<article class="member-card"><span class="member-avatar">${member.initials}</span><div><h3>${member.name}</h3><p>${member.joined}</p><span class="member-meta">${member.loans} active loan${member.loans === 1 ? '' : 's'}</span></div></article>`).join(''); }
function filteredBooks() { const query = ($('#catalog-search')?.value || '').toLowerCase(); const filter = $('#status-filter')?.value || 'all'; return books.filter((book) => (!query || `${book.title} ${book.author} ${book.category}`.toLowerCase().includes(query)) && (filter === 'all' || (filter === 'loaned' ? book.loaned : !book.loaned))); }
function activityMarkup(activity) { return `<div class="activity-item"><span class="activity-avatar">${activity.initials}</span><div class="activity-copy"><strong>${activity.name}</strong> ${activity.action} <strong>${activity.book}</strong><small>${activity.time}</small></div><span class="activity-type">${activity.action === 'returned' ? 'Return' : 'Loan'}</span></div>`; }
function showView(view) { document.querySelectorAll('.view').forEach((panel) => panel.classList.toggle('active-view', panel.dataset.viewPanel === view)); document.querySelectorAll('.nav-item').forEach((item) => item.classList.toggle('active', item.dataset.view === view)); const titles = { dashboard: 'Good morning, Jordan', catalog: 'Your catalog, in order', members: 'The people behind the books', activity: 'A little library history' }; $('#page-title').innerHTML = `${titles[view]} <span>✦</span>`; }
document.addEventListener('click', (event) => { const nav = event.target.closest('[data-view]'); if (nav) { event.preventDefault(); showView(nav.dataset.view); } const loanButton = event.target.closest('[data-loan]'); if (loanButton) { books[loanButton.dataset.loan].loaned = !books[loanButton.dataset.loan].loaned; localStorage.setItem('leaf-ledger-books', JSON.stringify(books)); render(); } });
['catalog-search', 'status-filter'].forEach((id) => document.getElementById(id).addEventListener('input', render));
['add-book-top', 'add-book-catalog'].forEach((id) => document.getElementById(id).addEventListener('click', () => $('#book-dialog').showModal()));
$('#book-form').addEventListener('submit', (event) => { event.preventDefault(); const data = new FormData(event.target); books.unshift({ title: data.get('title'), author: data.get('author'), category: data.get('category'), copies: Number(data.get('copies')), loaned: false }); localStorage.setItem('leaf-ledger-books', JSON.stringify(books)); event.target.reset(); $('#book-dialog').close(); render(); showView('catalog'); });
render();